<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AzureProxy</RootNamespace>
    <AssemblyName>AzureProxy</AssemblyName>
  </PropertyGroup>
  
  <!-- Fix for Linux publish -->
  <PropertyGroup>
    <PublishReadyToRun>false</PublishReadyToRun>
    <SelfContained>false</SelfContained>
  </PropertyGroup>
</Project>
